services:
  - type: web
    name: shl-fastapi-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 9000
    envVars:
      - key: PORT
        value: 9000
    plan: free